backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor

media_folder: static/asset
public_folder: /asset

collections:
  - name: post
    label: Blog
    folder: src/content
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {label: "tamplate", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "date", name: "date", widget: "datetime"}
      - {label: "author", name: "author", widget: "select", options: ["Helve", "Delusion"]}
      - {label: "Tags", name: "tags", widget: "select", options: ["React", "JavaScript", "FrontEnd", "cpp", "LeetCode"], multiple: true}
      - {label: "image", name: "image", widget: image, default: "img/writing.jpg", required: false}
      - {label: "body", name: "body", widget: "markdown"}

